# Generated by Django 5.2.8 on 2025-11-15 12:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('email', models.EmailField(max_length=100, unique=True, verbose_name='이메일')),
                ('password', models.CharField(max_length=255, verbose_name='비밀번호')),
                ('username', models.CharField(max_length=30, verbose_name='이름')),
                ('nickname', models.CharField(max_length=30, verbose_name='닉네임')),
                ('phone_number', models.CharField(max_length=15, verbose_name='휴대폰번호')),
                ('is_staff', models.BooleanField(default=False, verbose_name='관리자권한')),
                ('status', models.CharField(choices=[('ready', '비활성화'), ('active', '활성화'), ('dormancy', '휴면상태')], default='ready', max_length=10, verbose_name='계정상태')),
                ('point_balance', models.IntegerField(default=0)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': '사용자',
                'verbose_name_plural': '사용자 목록',
                'db_table': 'user',
            },
        ),
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('address_name', models.CharField(max_length=30, verbose_name='배송지명')),
                ('recipient', models.CharField(max_length=30, verbose_name='수취인')),
                ('recipient_phone', models.CharField(max_length=15, verbose_name='수취인번호')),
                ('post_code', models.CharField(max_length=10, verbose_name='우편번호')),
                ('address', models.CharField(max_length=200, verbose_name='주소')),
                ('detail_address', models.CharField(max_length=200, verbose_name='상세주소')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='addresses', to=settings.AUTH_USER_MODEL, verbose_name='사용자')),
            ],
            options={
                'verbose_name': '배송지',
                'verbose_name_plural': '배송지 목록',
                'db_table': 'addresses',
                'ordering': ('-updated_at',),
            },
        ),
        migrations.CreateModel(
            name='Point',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('amount', models.IntegerField(default=0, verbose_name='포인트 잔액')),
                ('balance', models.IntegerField(verbose_name='포인트 변화량')),
                ('event_key', models.CharField(blank=True, max_length=120, null=True, unique=True, verbose_name='이벤트 키')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='points', to=settings.AUTH_USER_MODEL, verbose_name='회원번호')),
            ],
            options={
                'verbose_name': '포인트 내역',
                'verbose_name_plural': '포인트 내역 목록',
                'db_table': 'points',
                'ordering': ('-updated_at',),
            },
        ),
        migrations.CreateModel(
            name='SocialLogin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('provider', models.CharField(choices=[('naver', 'naver')], max_length=50, verbose_name='제공자')),
                ('provider_user_id', models.BigIntegerField(verbose_name='제공자 측 고유 ID')),
                ('access_token', models.TextField(verbose_name='엑세스 토큰')),
                ('refresh_token', models.TextField(verbose_name='리프레쉬 토큰')),
                ('point_balance', models.IntegerField(default=0, verbose_name='포인트 잔액')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='social_logins', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '소셜 로그인',
                'verbose_name_plural': '소셜 로그인 목록',
                'db_table': 'social_login',
                'constraints': [models.UniqueConstraint(fields=('provider', 'provider_user_id'), name='unique_social_provider_user')],
            },
        ),
    ]
