# Generated by Django 5.2.8 on 2025-11-15 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='is_default',
            field=models.BooleanField(default=False, verbose_name='기본 배송지 여부'),
        ),
        migrations.AlterField(
            model_name='point',
            name='amount',
            field=models.IntegerField(verbose_name='포인트 변화량'),
        ),
        migrations.AlterField(
            model_name='point',
            name='balance',
            field=models.IntegerField(default=0, verbose_name='포인트 잔액'),
        ),
    ]
