# Generated by Django 5.2.8 on 2025-11-17 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_address_is_default_alter_point_amount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sociallogin',
            name='provider_user_id',
            field=models.CharField(max_length=255, verbose_name='제공자 측 고유 ID'),
        ),
    ]
