# Generated by Django 5.2.8 on 2025-11-15 12:57

import django.db.models.deletion
import utils.upload_paths
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Keyword',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keyword_type', models.CharField(choices=[('positive', '긍정'), ('neutral', '중립'), ('negative', '부정')], max_length=15)),
                ('keyword_name', models.CharField(max_length=15, unique=True)),
            ],
            options={
                'verbose_name': '키워드',
                'verbose_name_plural': '키워드 목록',
                'db_table': 'keywords',
            },
        ),
        migrations.CreateModel(
            name='ReviewImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('review_image', models.ImageField(upload_to=utils.upload_paths.general_upload_to)),
            ],
            options={
                'verbose_name': '리뷰이미지',
                'verbose_name_plural': '리뷰이미지 목록',
                'db_table': 'review_images',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ReviewKeyword',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'review_keywords',
            },
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('review_title', models.CharField(max_length=50)),
                ('content', models.TextField()),
                ('rating', models.DecimalField(decimal_places=1, default=0, max_digits=2)),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='product_reviews', to='products.product')),
            ],
            options={
                'verbose_name': '리뷰',
                'verbose_name_plural': '리뷰 목록',
                'db_table': 'reviews',
                'ordering': ['-created_at'],
            },
        ),
    ]
