# Generated by Django 5.2.8 on 2025-11-15 12:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('reviews', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_reviews', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='reviewimage',
            name='review',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='review_images', to='reviews.review'),
        ),
        migrations.AddField(
            model_name='reviewkeyword',
            name='keyword',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='keyword_reviews', to='reviews.keyword'),
        ),
        migrations.AddField(
            model_name='reviewkeyword',
            name='review',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='review_keywords', to='reviews.review'),
        ),
        migrations.AddField(
            model_name='review',
            name='keywords',
            field=models.ManyToManyField(related_name='reviews', through='reviews.ReviewKeyword', to='reviews.keyword'),
        ),
        migrations.AddConstraint(
            model_name='reviewkeyword',
            constraint=models.UniqueConstraint(fields=('review', 'keyword'), name='unique_review_keyword'),
        ),
    ]
