# Generated by Django 5.2.8 on 2025-11-15 12:57

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('subtotal', models.PositiveIntegerField(default=0, verbose_name='상품 총합')),
                ('discount_amount', models.PositiveIntegerField(default=0, verbose_name='할인 금액')),
                ('delivery_amount', models.PositiveIntegerField(default=0, verbose_name='배송비')),
                ('delivery_request', models.CharField(blank=True, max_length=100, null=True, verbose_name='배송 시 요청사항')),
                ('total_payment', models.PositiveIntegerField(default=0, verbose_name='최종 결제 금액')),
                ('used_point', models.IntegerField(default=0, verbose_name='사용된 적립금')),
                ('order_status', models.CharField(choices=[('접수 완료', '접수 완료'), ('주문 실패', '주문 실패'), ('주문 완료', '주문 완료')], default='접수 완료', max_length=15, verbose_name='주문상태')),
                ('delivery_status', models.CharField(choices=[('배송 준비', '배송 준비'), ('배송 중', '배송 중'), ('배송 완료', '배송 완료')], default='배송 준비', max_length=15, verbose_name='배송상태')),
                ('order_number', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='주문번호(노출용)')),
            ],
            options={
                'verbose_name': '주문',
                'verbose_name_plural': '주문 목록',
                'db_table': 'orders',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OrderProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('amount', models.PositiveIntegerField(blank=True, default=1, null=True, verbose_name='상품수량')),
                ('price', models.PositiveIntegerField(verbose_name='상품 주문 당시 가격')),
                ('total_price', models.PositiveIntegerField(verbose_name='상품 총 금액')),
            ],
            options={
                'verbose_name': '주문 상품',
                'verbose_name_plural': '주문 상품 목록',
                'db_table': 'order_products',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('payment_status', models.CharField(choices=[('ready', 'ready'), ('success', 'success'), ('failed', 'failed')], default='ready', max_length=15, verbose_name='결제상태')),
                ('payment_method', models.CharField(choices=[('tosspay', 'tosspay')], default='tosspay', max_length=15, verbose_name='결제수단')),
                ('payment_amount', models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='결제금액')),
                ('toss_order_id', models.CharField(db_index=True, max_length=100, unique=True)),
                ('toss_payment_key', models.CharField(blank=True, db_index=True, max_length=200, null=True)),
                ('receipt_url', models.URLField(blank=True, null=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('fail_code', models.CharField(blank=True, max_length=50, null=True)),
                ('fail_message', models.CharField(blank=True, max_length=255, null=True)),
                ('idempotency_key', models.CharField(blank=True, db_index=True, max_length=64, null=True)),
            ],
            options={
                'verbose_name': '결제',
                'verbose_name_plural': '결제 목록',
                'db_table': 'payments',
            },
        ),
    ]
