# Generated by Django 5.2.8 on 2025-11-15 12:57

import django.db.models.deletion
import utils.upload_paths
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand_name', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'verbose_name': '브랜드',
                'verbose_name_plural': '브랜드 목록',
                'db_table': 'brands',
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=15, unique=True)),
            ],
            options={
                'verbose_name': '카테고리',
                'verbose_name_plural': '카테고리 목록',
                'db_table': 'categories',
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag_name', models.CharField(max_length=15, unique=True)),
            ],
            options={
                'verbose_name': '태그',
                'verbose_name_plural': '태그 목록',
                'db_table': 'tags',
            },
        ),
        migrations.CreateModel(
            name='BrandImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('brand_image', models.ImageField(upload_to=utils.upload_paths.general_upload_to)),
                ('brand', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='brand_images', to='products.brand')),
            ],
            options={
                'verbose_name': '브랜드 이미지',
                'verbose_name_plural': '브랜드 이미지 목록',
                'db_table': 'brand_images',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product_name', models.CharField(max_length=100)),
                ('product_value', models.IntegerField()),
                ('product_stock', models.IntegerField()),
                ('discount_rate', models.DecimalField(decimal_places=2, default=0, max_digits=3)),
                ('product_rating', models.DecimalField(decimal_places=1, default=0, max_digits=2)),
                ('sales', models.IntegerField(default=0)),
                ('brand', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='products.brand')),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='products.category')),
            ],
            options={
                'verbose_name': '상품',
                'verbose_name_plural': '상품목록',
                'db_table': 'products',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product_card_image', models.ImageField(upload_to=utils.upload_paths.general_upload_to)),
                ('product_explain_image', models.ImageField(upload_to=utils.upload_paths.general_upload_to)),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='product_images', to='products.product')),
            ],
            options={
                'verbose_name': '상품 이미지',
                'verbose_name_plural': '상품 이미지 목록',
                'db_table': 'product_images',
            },
        ),
        migrations.CreateModel(
            name='ProductQna',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('question_type', models.CharField(choices=[('inquiry', '문의'), ('suggestion', '건의')], max_length=15)),
                ('question_title', models.CharField(max_length=50)),
                ('question_content', models.TextField()),
                ('question_answer', models.TextField(blank=True, null=True)),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='qnas', to='products.product')),
            ],
            options={
                'verbose_name': '상품 문의',
                'verbose_name_plural': '상품 문의 목록',
                'db_table': 'product_qna',
                'ordering': ['-created_at'],
            },
        ),
    ]
